config/routes.rb
Rails.application.routes.draw do
  
  get 'course_search/index'
  get 'course_search/update_courses', as: 'update_courses'
  get 'welcome/show'

  get 'main/home'
  

  get 'sessions/login'
  resources :subjects do
    resources :courses do
       resources :resources
    end
  end

  root 'main#home'
  match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :subject
  has_many :resources
end

app/models/resource.rb
class Resource < ActiveRecord::Base

	#scope :status, -> (status) { where status: status }
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
 	validates :name, presence: true # Make sure the owner's name is present.
 	validates :attachment, presence: true
 	belongs_to :course
 	scope :course_id, -> (course_id) {where course_id: course_id}
 	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :courses
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	#attr_accessor :password,:password_confirmation
	EMAIL_REGEX = /\A[A-Z0-9._%+-]+@ucalgary+\.ca\z/i
	
	validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :faculty, :presence => true
	validates :major, :presence => true
  	validates :email, :presence => true, :uniqueness => true , :format => EMAIL_REGEX
  	validates :password, :confirmation => true   #password_confirmation attr
  	validates :password_confirmation, :presence => true, :if => Proc.new { |user| user.new_record? }




=begin
def self.authenticate(username_email = "", login_password = "")
	if EMAIL_REGEX.match(username_email)
		user = User.find_by_email(username_email)
	else
		user = User.find_by_username(username_email)
	end

	if user && User.match_password(login_password)
		return user 
	else
		return false
	end

def match_password(login_password="")
  encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
end 
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/course_search_controller.rb
class CourseSearchController < ApplicationController
  def index
  	@subjects = Subject.all
  	@courses = Course.where("subject_id = ?", Subject.first.id)
  end
  
  def show
  	@course = Course.find_by("id = ?", params[:trip][:course_id])
    @subject = Subject.find_by("id = ?", params[:trip][:subject_id])
    #redirect_to(url_for(subject_course_resources_path(params[:subject_id], params[:course_id])))
    redirect_to(url_for(subject_course_resources_path(@subject,@course)))
  end
  
  def update_courses
  	@courses = Course.where("subject_id = ?", params[:subject_id])
  	respond_to do |format|
  		format.js
  	end
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
    def index
      #where(<columnname> => <columnvalue>)
      @resources = Resource.all
      @resources = @resources.course_id(params[:course_id]) if params[:course_id].present?
   end
   
   def new
      @resource = Resource.new
   end
   def create
      @resource = Resource.new(resource_params)
      @resource.course_id = params[:course_id]
      
      if @resource.save
         

         redirect_to subject_course_resources_path, notice: "The Resource #{@resource.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @resource = Resource.find(params[:id])
      @resource.destroy
      redirect_to subject_course_resources_path, notice:  "The Resource #{@resource.name} has been deleted."
   end
   
   private
      def resource_params
      params.require(:resource).permit(:name, :attachment)
   end
   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  	#Login form
  end

  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user = User.where(:email => params[:email]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end

    end

    if authorized_user && !authorized_user.email_checked
      session[:user_id]= authorized_user.id
      session[:username]= authorized_user.username

      redirect_to(:action => "validate_email")
    
   

    elsif authorized_user
      #mark user as logged in
      
      session[:user_id]= authorized_user.id
      session[:username]= authorized_user.username
      @username = authorized_user.username
      flash[:notice] = "You are now logged in."
      redirect_to(:action => 'home')
    
    else
      flash[:notice] = "Invalid username/password combination."
      redirect_to(:action => 'login')
    end
  end

  def logout
    # mark user as logged out
    session[:user_id]= nil
    session[:username]= nil
    flash[:notice] = "Logged out"
    redirect_to(:controller => "Main", :action => "home")
  end

  #Prompt to ask to change password(user does not have to)
  def validate_email
    
    user = User.where(:id => session[:user_id]).first
    if params[:password].present? && params[:confirm_password].present?
      
      if params[:password] != params[:confirm_password]
       flash[:notice] = "The passwords you entered don't seem to match."
      
      elsif result = change_password(user.id, params[:password], params[:confirm_password])
        user.email_checked = true
        user.save!

        redirect_to(:action => 'home')
      end
        #send email to let user know
       
      
    end
    

  end

  def forgot_password
   user = User.where(:email => params[:email]).first
   if params[:email].present? && user.present?
    VerifyEmail.send_password_forgot(user).deliver_now
    flash[:notice] = " Your password has been reset, just wait for the email and login with your randomly generated password!"
    redirect_to(:action => 'login')
   elsif !params[:email].blank?
     
    flash[:notice] = " Looks like that email isn't in our records, check your email or go ahead and signup!"
   end
  end



  private
  def change_password(id, password, confirm_password)
    user = User.where(:id => id).first
    if password == confirm_password
      user.password = password
      user.password_confirmation = confirm_password
      user.save!
      return true
    end
    return false
  end


  public
  def home
    if session[:user_id] == nil || session[:username] == nil
      redirect_to(:action => 'login')
    end

  	#Home Page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout false

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		
		
		if @user.save
			flash[:notice] = "Sign Up Successful"
			flash[:color] = "valid"
			VerifyEmail.send_verification(@user).deliver_now
			redirect_to(:controller =>'Sessions' , :action => 'login')
		else
			flash[:color] = "invalid"
			render ('new')
		end
	end

	private 
	def user_params
    	params.require(:user).permit(:username, :faculty, :major, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_search_helper.rb
module CourseSearchHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/course_search/index.html.erb
<!-- app/views/welcome/index.html.erb -->
  
<link href="main.css" rel="app/stylesheets" type="text/scss"/>﻿

<%= form_for :trip, url: {action: "show"}, html: {method: "post"} do |f| %>
  <%= f.select :subject_id, options_for_select(@subjects.collect { |subject|
    [subject.name.titleize, subject.id] }, 1), {}, { id: 'subjects_select' } %>
  <%= f.select :course_id, options_for_select(@courses.collect { |course|
    [course.course_number, course.id] }, 0), {}, { id: 'courses_select' } %>
  <%= f.submit "Go!" %>
<% end %>

app/views/course_search/show.html.erb
<!-- app/views/welcome/show.html.erb -->
  
<p><%= @course.course_number%></p>
<br />
<%= link_to("Back to Search", {:controller => "course_search",:action => 'index'}, :class => 'action index') %>

<%= @course.resources %>

app/views/courses/_course.html.erb
<option value="<%= course.id %>"><%= course.course_number%></option>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebMess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
      <div class="row">
        <div class="col-xs-1">
            <h1>U•VIDA</h1></div>
        <div class="col-xs-10"></div>
        <div class="col-xs-1">
          <div class="dropdown">
            <button id= dropdown-button class="btn btn primary dropdown-toggle" type="button" data-toggle="dropdown"> <img src = "/icons/dropdown.ico"></img></button>    
            <ul class="dropdown-menu">
              <li><%= link_to("Login", {:controller => "Sessions",:action => 'login'}, :class => 'action login') %></li> 
            </ul>
          </div>
        </div>
      </div>
  </div>

  <div class="container-responsive">
    <div class="row">
      <div align = "center" class="col-xs-12">
      <%= yield %>
      </div>
    </div>
  </div>

  <div class="container" id= "container-2">
    <div class="row">
      <div class="col-xs-12">
      <p id="text">
      <br>
        The halting problem is highly non trivial.
      </p>
        <h2>- Peter Hoyer</h2>
        <br>
      </div>
    </div>
  </div>

    <div class="container" id= "container-3">
      <div class="row">
      
          <div class="col-xs-4" align="center">
          <%= link_to "Desire to Learn", "https://d2l.ucalgary.ca/login.asp" "\n"%>
          </div>
      
          <div class="col-xs-4" align="center">
          <%= link_to "University of Calgary", "https://www.ucalgary.ca/" %>
          </div>

          <div class="col-xs-4" align="center">
          <%= link_to "Campus Map", "http://ucmaps.ucalgary.ca/PublicFiles/CurrentMaps/CampusMap_MainCampus_Letter.pdf" %>
          </div>
                    <div class="col-xs-4" align="center">
          <%= link_to "Resources", {:controller => 'course_search', :action => 'index'} %>
          </div>
      </div>
      <br>
    </div>

</body>
</html>

app/views/main/home.html.erb
<% if !flash[:notice].blank? %>
	<div class = "notice">
		<%= flash[:notice] %>
	</div>
<%end%>

<div id="container">
  <img src="/images/mainbackground.jpg" id="background-home">
	 <div class="col-xs-6">
		<p id="text-1">
		School is hard enough
		</p>
  </div>
 	
    <div class="col-xs-6">
	     <%= form_for(:user, :url => {:controller => 'Users', :action => 'new'}) do |f| %>
		  <table summary="Users form fields" id="user-input">
        <tr>
        	<th id="user-form">Username &nbsp; &nbsp; </th>
        	<td><%= f.text_field(:username)%></td>
      	</tr>
          <br>
      	<tr>
        	<th id="user-form">Email</th>
        	<td><%= f.text_field(:email) %></td>
      	</tr>
          <br>
      	<tr>
        	<th id="user-form">Password</th>
        	<td><%= f.password_field(:password) %></td>
      	</tr>
	   </table>
    <button class= "button" type="submit" value="Submit">SIGN UP!</button>
  	<%end%>
	</div>
</div>

app/views/resources/create.html.erb
<h1>Resources#create</h1>
<p>Find me in app/views/resources/create.html.erb</p>

app/views/resources/destroy.html.erb
<h1>Resources#destroy</h1>
<p>Find me in app/views/resources/destroy.html.erb</p>

app/views/resources/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />
<h><b>Course Resources</b></h> 

</br>
<%= link_to "<< Back to Course Search", {:controller => 'course_search', :action => 'index' }%>

</br>
</br>
<%= link_to "New Resource", new_subject_course_resource_path, class: "btn btn-primary" %>
<br />
<br />




<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
      </tr>
   </thead>
   
   <tbody>
      <% @resources.each do |resource| %>
         <tr>
            <td><%= resource.name %></td>
            <td><%= link_to "Download resource", resource.attachment_url %></td>
              
         </tr>
      <% end %>
   </tbody>
   
</table>

app/views/resources/new.html.erb
<% if !@resource.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resource.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
   

<% end %>

<div class = "well.. why doesn't this work?">
   <%= form_for @resource,:url => {:action => 'create'}, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/users/home.html.erb
<h1>This is the user home page</h1>
<% if !flash[:notice].blank? %>
	<div class = "notice">
		<%= flash[:notice] %>
	</div>
<%end%>

<%= link_to("Sign Up", {:action => 'new'}, :class => 'action new') %>
</br>
<%= link_to("Login", {:controller => "Sessions",:action => 'login'}, :class => 'action login') %>
</br>

app/views/users/new.html.erb
<% @page_title = "Sign Up" %>
<%= link_to("<< Back to Home", {:controller => "Main",:action => 'home'}, :class => 'back-link') %>
<div class="users new">
  <h2>Sign Up</h2>
    <%= form_for(:user, :url => {:action => 'create'}) do |f| %>

    <table  align="center" summary="Users form fields">
      <tr>
        <th>Username (at least 3 characters)</th>
        <td><%= f.text_field(:username) %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= f.text_field(:email) %></td>
      </tr>
      <tr>
        <th>Password</th>
        <td><%= f.password_field(:password) %></td>
      </tr>
      <tr>
        <th>Confirm Password</th>
        <td><%= f.password_field(:password_confirmation) %></td>
      </tr>
      <tr>
        <th>Faculty</th>
        <td><%= f.text_field(:faculty) %></td>
      </tr>
      <tr>
        <th>Major</th>
        <td><%= f.text_field(:major) %></td>
      </tr>

    </table>

    <div class="form-buttons">
      <%= submit_tag("Sign Up") %>
    </div>

  <% end %>

  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li> <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/verify_email/send_password_forgot.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
	</head>
<body>




 <h1><b>WebMess Resources</b></h1>
 <h3>We got your password reset right here! We sent you a randomly generated password, just sign in using your email and that password and change your password when you login!</h3>
 <h3>Here's your password</h3>
 <h2><b><%=@reset_password%></b></h2>







</body>
</html>

app/views/verify_email/send_verification.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
	</head>
<body>

 <h1><b>WebMess Resources</b></h1>
 <h3>Thanks for signing up with WebMess Resources! We sent you a randomly generated, just sign in using your email and that password and your set!</h3>
 <h3>Here's your password</h3>
 <h2><b><%=@default_password%></b></h2>








</body>
</html>